defmodule KiteAgentHubWeb.API.ScoreControllerTest do
  use KiteAgentHubWeb.ConnCase, async: true

  import KiteAgentHub.TradingFixtures

  alias KiteAgentHub.Repo

  # Auth for these endpoints is a Bearer agent api_token — seed one.
  # All of these tests target validation paths that fail BEFORE any
  # Alpaca HTTP call, so credential setup is intentionally skipped
  # (the controller should 400 on bad params regardless of creds).
  setup do
    %{agent: agent} = agent_scope_fixture()

    # The api_token is generated by the schema's changeset. Reload with
    # the unscoped Repo so the controller's cross-org lookup can find it.
    agent = Repo.reload!(agent)

    {:ok, agent: agent}
  end

  defp auth(conn, agent), do: put_req_header(conn, "authorization", "Bearer " <> agent.api_token)

  describe "GET /api/v1/score" do
    test "401 when no bearer token", %{conn: conn} do
      conn = get(conn, ~p"/api/v1/score?ticker=AAPL")
      assert json_response(conn, 401) == %{"ok" => false, "error" => "invalid api key"}
    end

    test "400 when ticker param is missing", %{conn: conn, agent: agent} do
      conn = conn |> auth(agent) |> get(~p"/api/v1/score")
      assert %{"ok" => false, "error" => error} = json_response(conn, 400)
      assert error =~ "ticker"
    end

    test "400 when timeframe is unsupported", %{conn: conn, agent: agent} do
      conn =
        conn
        |> auth(agent)
        |> get(~p"/api/v1/score?ticker=AAPL&timeframe=1Year")

      assert %{"ok" => false, "error" => error} = json_response(conn, 400)
      assert error =~ "timeframe"
    end

    test "400 when limit is out of range", %{conn: conn, agent: agent} do
      conn = conn |> auth(agent) |> get(~p"/api/v1/score?ticker=AAPL&limit=0")
      assert %{"error" => error} = json_response(conn, 400)
      assert error =~ "limit"

      conn2 =
        build_conn()
        |> auth(agent)
        |> get(~p"/api/v1/score?ticker=AAPL&limit=50000")

      assert %{"error" => error2} = json_response(conn2, 400)
      assert error2 =~ "limit"
    end

    test "accepts each supported timeframe past param validation", %{conn: conn, agent: agent} do
      # No Alpaca creds are seeded, so past validation we expect the
      # credentials-not-configured branch (400), not a bad_timeframe.
      for tf <- ~w(1Min 5Min 15Min 1Hour 1Day) do
        resp =
          build_conn()
          |> auth(agent)
          |> get(~p"/api/v1/score?ticker=AAPL&timeframe=#{tf}")
          |> json_response(400)

        refute resp["error"] =~ "timeframe"
        assert resp["error"] =~ "alpaca credentials"
      end
    end
  end

  describe "POST /api/v1/score/batch" do
    test "401 when no bearer token", %{conn: conn} do
      conn = post(conn, ~p"/api/v1/score/batch", %{tickers: ["AAPL"]})
      assert json_response(conn, 401)["ok"] == false
    end

    test "400 when tickers is missing or empty", %{conn: conn, agent: agent} do
      for body <- [%{}, %{tickers: []}, %{tickers: "AAPL"}] do
        resp =
          build_conn()
          |> auth(agent)
          |> post(~p"/api/v1/score/batch", body)
          |> json_response(400)

        assert resp["error"] =~ "tickers"
      end
    end

    test "400 when any ticker in the list is malformed", %{conn: conn, agent: agent} do
      resp =
        conn
        |> auth(agent)
        |> post(~p"/api/v1/score/batch", %{tickers: ["AAPL", "bad ticker!!!"]})
        |> json_response(400)

      assert resp["error"] =~ "tickers"
    end

    test "400 when batch exceeds the 25-ticker cap", %{conn: conn, agent: agent} do
      too_many = Enum.map(1..30, fn i -> "T#{i}" end)

      resp =
        conn
        |> auth(agent)
        |> post(~p"/api/v1/score/batch", %{tickers: too_many})
        |> json_response(400)

      assert resp["error"] =~ "25"
    end
  end
end
